name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  Deploy:
    name: sequence2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf eddy.war * && ls
